name: Docker Image CI

on:
  push:
    branches: [ "deployed" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2      
      with:
        project_id: 'ecomscraper'
        workload_identity_provider: 'projects/686267651726/locations/global/workloadIdentityPools/pool1/providers/aws1'
               
          
    - name: Build the Docker image
      run: |-
        cd ottpApi
        docker build -t ottpapi .
        docker tag ottpapi:latest asia-south1-docker.pkg.dev/ecomscraper/images/ottpapi:latest
        docker push asia-south1-docker.pkg.dev/ecomscraper/images/ottpapi:latest
        gcloud run deploy \
            --image=asia-south1-docker.pkg.dev/ecomscraper/images/ottpapi:latest \
            --platform=managed \
            --region=asia-south1 \
            --allow-unauthenticated
